-- begin CRUISESAMPLE_ROUTE_PORT_LINK
alter table CRUISESAMPLE_ROUTE_PORT_LINK add constraint FK_CRPL_ROUTE foreign key (ROUTE_ID) references CRUISESAMPLE_ROUTE(ID)^
alter table CRUISESAMPLE_ROUTE_PORT_LINK add constraint FK_CRPL_PORT foreign key (PORT_ID) references CRUISESAMPLE_PORT(ID)^
-- end CRUISESAMPLE_ROUTE_PORT_LINK
-- begin CRUISESAMPLE_WAYPOINT
alter table CRUISESAMPLE_WAYPOINT add constraint FK_CRUISESAMPLE_WAYPOINT_ROUTE foreign key (ROUTE_ID) references CRUISESAMPLE_ROUTE(ID)^
create index IDX_CRUISESAMPLE_WAYPOINT_ROUTE on CRUISESAMPLE_WAYPOINT (ROUTE_ID)^
-- end CRUISESAMPLE_WAYPOINT
