alter table CRUISESAMPLE_STOP add constraint FK_CRUISESAMPLE_STOP_ON_PORT foreign key (PORT_ID) references CRUISESAMPLE_PORT(ID);
create index IDX_CRUISESAMPLE_STOP_ON_PORT on CRUISESAMPLE_STOP (PORT_ID);
